book.json
Simple fix, otherwise the book won't compile:
``` bash
> gitbook pdf . ./book.pdf
info: loading book configuration....OK 
info: >> 0 plugins loaded 
No README file
npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.38
npm ERR! npm  v2.10.0
npm ERR! code ELIFECYCLE
npm ERR! survivejs-webpack@0.1.0 start: `gitbook pdf . ./book.pdf`
npm ERR! Exit status 1
```
=> Fix book.json

manuscript/06_react_and_flux.md, manuscript/07_from_notes_to_kanban.md
Fixed 3 errors on Windows, by converting "inject {{ ... }}" => "inject { { ... } }", just as in AltContainer docs.
Fixed errors:
Template render error: (X:\git\webpack_react_my\manuscript\06_react_and_flux.md) [Line 545, Column 18]
expected variable end (In file 'manuscript/06_react_and_flux.md')
Template render error: (X:\git\webpack_react_my\manuscript\07_from_notes_to_kanban.md) [Line 42, Column 18]
expected variable end (In file 'manuscript/07_from_notes_to_kanban.md')
Template render error: (X:\git\webpack_react_my\manuscript\07_from_notes_to_kanban.md) [Line 42, Column 18]
expected variable end (In file 'manuscript/07_from_notes_to_kanban.md')
=> fix compatibility problem for building on Windows

README.md
Add instructions for generating an ebook using OS X. Homebrew does not
contain a formula for Calibre as it is a GUI application, so
Homebrew-cask is the alternative. I found that generating an ebook
required adding the Calibre CLI to my PATH, as referenced in
https://github.com/GitbookIO/gitbook/issues/333#issuecomment-64134770.
=> Docs: Add OS X instructions

manuscript/07_from_notes_to_kanban.md
In fact there are two commits here, one is about a typo. 
And the other one adds an explanation for the string parameter in `createStore`. I think it's better to either remove it or to explain why it's there.
=> Alt create store comment

manuscript/00_introduction.md
Change Javascript to JavaScript to match formatting in the rest of the 00_introduction.md.
=> Correct formatting of JavaScript in introduction

manuscript/02_getting_started.md
When loading the first webpack generated `bundle.js` file in the 02_getting_started.md file it 404'd until I updated the script path in body to match the path laid out for `bundle.js` in [Directory Structure](https://github.com/survivejs/webpack_react/blob/master/manuscript/02_getting_started.md#directory-structure) section.
=> Update path to bundle.js in 02_getting_started.md index.html file.

project_source/build_all.sh
It defeats the purpose if an user needs to go to each project to install the dependencies. Useful is someone wants to try the `site` repo.
=> Update build_all.sh to include NPM dependencies

manuscript/11_linting_in_webpack.md
origin state created this warning:
WARNING in ./~/css-loader!./~/postcss-loader!./app/main.css
stylelint: Expected option value for rule "color-hex-case"
changing to lower and using upper for color-hex creates this warning (intended with the example):
WARNING in ./~/css-loader!./~/postcss-loader!./app/main.css
stylelint: /Users/mitch/Learn/surviveJS/kanban_app/app/main.css:2:3: Expected "#F0F0F0" to be "#f0f0f0" (color-hex-case)
https://github.com/stylelint/stylelint/tree/master/src/rules/color-hex-case
=> fixed ch11 linting css example

manuscript/14_language_features.md
Add a section to explain what are the differences and how the **ES6 classes** works when using `export default class` and `export class` with **ES6 modules**.
=> classes and modules for ES6

manuscript/04_implementing_notes.md
Webpack will not build, complain, and correctly point out the syntax error.
=> Missing last semicolon for addNote() declaration

manuscript/05_react_and_flux.md
At this point however, the deletion may be implied with the change to AltContainer. Not sure if you want to include it. But the app will error saying 'this.state is null' in browser console.
=> Skipped deletion

manuscript/07_implementing_dnd.md
I tried to get rid of the word "target" in relation to "dragged", as I personally found the implicit distinction between dragged target and drop target confusing. But your mileage may vary, of course.
=> Suggestions for language changes

manuscript/02_developing_with_webpack.md
There isn't a need to insert a '],' there, but I think it was supposed to be a '},' to help guide the reader where to put the code.
=> Fix bracket consistency between sections

manuscript/06_from_notes_to_kanban.md
we're starting to work on Editable.jsx (copied from Note.jsx).
our first step should be replacing "class Note" with "class
Editable" not the other way around.
=> Editable, Note insert/delete swapped

manuscript/11_linting_in_webpack.md
There was an 'x' missing from the jshint example webpack config, in the filename test. This changes adds it.
=> Fix jshint sample webpack config to support JSX

manuscript/07_implementing_dnd.md
This seems to work without the proposed fix at least with react-dnd 2.1.3.
=> isDragging doesn't lose it state anymore.

manuscript/04_implementing_notes.md
Not sure how to link inside the document. 
can link to the [language feature](https://github.com/survivejs/webpack_react/blob/dev/manuscript/15_language_features.md#object-shorthands) section as well 
also the language feature calls it `Object Shorthands` but the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) calls it `Object initializer`
=> Add link to Object initializer in implementing_notes

manuscript/07_implementing_dnd.md, project_source/07_implementing_dnd/kanban_app/app/stores/LaneStore.js
After adding code to filter out the note, the second `if(lane.notes.includes(noteId))` statement doesn't seem necessary.
=> Removing unreachable if condition

manuscript/appendices/01_language_features.md
These are other two issues [I reported](http://survivejs.com/react/appendices/language-features/#comment-2754511393) this morning (maybe you didn't see them because I left too much space after the first one and Disqus hides the second part of long comments)
=> Language features typos

manuscript/getting_started/04_deleting_notes.md
A missing "we" in a sentence and an unnecessary comma in some code.
=> Minor typos fixed

manuscript/appendices/01_language_features.md
Both the counter and the result array were constants, which caused a syntax error as they tried to mutate.
=> Changed `const` to `let` in es6 Array.map example
