- manuscript/05_implementing_notes.md
Got no "edited" prop at this point so null object error
> App.jsx listing

- manuscript/webpack_compared.md
According to https://docs.npmjs.com/misc/faq#is-it-npm-or-npm-or-npm npm is never capitalized.
> Fix display of npm

- manuscript/implementing_notes.md
This comma should not be there
> removed comma

- manuscript/developing_with_webpack.md
> the .tpl configuration is not needed anymore.

- manuscript/01_webpack_compared.md
- manuscript/02_getting_started.md
- manuscript/08_from_notes_to_kanban.md
- manuscript/10_implementing_dnd.md
- manuscript/11_deploying_applications.md
- manuscript/12_authoring_libraries.md
I fixed some small typos and made some small textual improvements while I was reading the book.
If you like, I could do a more thorough read-through, and provide another pull request?
P.S. I really liked reading the book, keep up the good work!
> Fixed some small typos / made some textual improvements

- manuscript/01_webpack_compared.md
"e.g." is "for example", "i.e." is "that is"...
> Change ie. to e.g.

- manuscript/01_webpack_compared.md
And to be utterly pedantic, when you do really mean "i.e." it's "i.e." not "ie.". ;-)
> ie. -> e.g.

- manuscript/07_from_notes_to_kanban.md
What lodash is for here? It works without it.
> 07 from singletons to instances fixes

- manuscript/04_webpack_and_react.md
Only made 1 grammatical change:
1) Instead of 'As', change to 'An'.
No other changes were made.
> Minor typo fix

- manuscript/05_implementing_notes.md
- manuscript/09_implementing_dnd.md
Just minor stuff that I spotted.
> Fix indentation & update findIndex to match the source codes

- manuscript/05_react_and_flux.md
"minimizing the amount of goal written"
> 05_react_and_flux.md - typo fix - 'goal' -> 'code'

- manuscript/05_react_and_flux.md
fixed: "if we wanted to do communicate with"
> 05_react_and_flux - typo fix

- manuscript/03_webpack_and_react.md
> Fix 'alternatively' typo

- manuscript/02_developing_with_webpack.md
> Minor grammar fixes in 02_developing_with_webpack

- manuscript/04_implementing_notes.md
- manuscript/06_from_notes_to_kanban.md
- project_source/04_implementing_notes/kanban_app/app/components/Note.jsx
- project_source/04_implementing_notes/kanban_app/app/main.css
- project_source/05_react_and_flux/kanban_app/app/components/Note.jsx
- project_source/05_react_and_flux/kanban_app/app/main.css
- project_source/06_from_notes_to_kanban/kanban_app/app/components/Editable.jsx
- project_source/06_from_notes_to_kanban/kanban_app/app/components/Note.jsx
- project_source/06_from_notes_to_kanban/kanban_app/app/main.css
- project_source/07_implementing_dnd/kanban_app/app/components/Editable.jsx
- project_source/07_implementing_dnd/kanban_app/app/main.css
- project_source/08_building_kanban/kanban_app/app/components/Editable.jsx
- project_source/08_building_kanban/kanban_app/app/main.css
- project_source/09_testing_react/kanban_app/app/components/Editable.jsx
- project_source/09_testing_react/kanban_app/app/main.css
- project_source/10_typing_with_react/flow_app/app/components/Editable.jsx
- project_source/10_typing_with_react/flow_app/app/main.css
- project_source/10_typing_with_react/proptypes_app/app/components/Editable.jsx
- project_source/10_typing_with_react/proptypes_app/app/main.css
[Issue #319](https://github.com/survivejs/webpack_react/issues/319): Use `delete-note` class name for consistency
> use `delete-note` class name for consistency

- manuscript/04_implementing_notes.md
- manuscript/05_react_and_flux.md
- manuscript/06_from_notes_to_kanban.md
- project_source/04_implementing_notes/kanban_app/app/components/App.jsx
- project_source/04_implementing_notes/kanban_app/app/components/Note.jsx
- project_source/05_react_and_flux/kanban_app/app/components/Note.jsx
- project_source/05_react_and_flux/kanban_app/app/stores/NoteStore.js
- project_source/06_from_notes_to_kanban/kanban_app/app/components/Editable.jsx
- project_source/06_from_notes_to_kanban/kanban_app/app/components/Note.jsx
- project_source/06_from_notes_to_kanban/kanban_app/app/stores/NoteStore.js
- project_source/07_implementing_dnd/kanban_app/app/components/Editable.jsx
- project_source/07_implementing_dnd/kanban_app/app/stores/NoteStore.js
- project_source/08_building_kanban/kanban_app/app/components/Editable.jsx
- project_source/08_building_kanban/kanban_app/app/stores/NoteStore.js
- project_source/09_testing_react/kanban_app/app/components/Editable.jsx
- project_source/09_testing_react/kanban_app/app/stores/NoteStore.js
- project_source/10_typing_with_react/flow_app/app/components/Editable.jsx
- project_source/10_typing_with_react/flow_app/app/stores/NoteStore.js
- project_source/10_typing_with_react/proptypes_app/app/components/Editable.jsx
- project_source/10_typing_with_react/proptypes_app/app/stores/NoteStore.js
This PR change the original behavior of the note's input field on edition as mentioned in the issue #322.
> Use input placeholder attribute on note edition

- README.md
> Update README.md with link to stackoverflow

- manuscript/04_implementing_notes.md
Thank you for all your work doing this book! :palm_tree:
> Fix small typo in hierarchy

- manuscript/08_building_kanban.md
It will not build without explicitly installing it as a dev dependency.
> Add npm install command for clean-webpack-plugin

- manuscript/02_developing_with_webpack.md
"build": "webpack"
->
"build": "webpack",
> fixed 02_developing_with_webpack.md

- manuscript/01_introduction.md
Using the Cambridge dictionary as a reference, confirmed that 'at' is more often used when referring to a speed or pace. 
> pace noun (SPEED)
> B2 [U] the speed at which someone or something moves, or with which something happens or changes:
Source: [Cambridge Dictionaries Online](http://dictionary.cambridge.org/dictionary/english/pace)
> Introduction: Fixed preposition describing pace of tech change

- manuscript/getting_started/03_implementing_notes.md
Changed "You should seem something" to "You should see something"
> Fixed typo in implementing-notes

- project_source/implementing_kanban/06_drag_and_drop/kanban-app/app/components/App.jsx
It was quite hard to understand the code at the first look for me ;)
> Make compose() a bit more readable

- manuscript/getting_started/02_setting_up_the_project.md
The procedure for removing the current git repository and creating a new one is included twice in this chapter: once as part of the download process, and again as a sidebar.  
It seems better to extract this to a separate section, to make it a single step, which may also be a useful reference for git newbies.  This also makes the later sidebar describing the same action repetitively redundant ;-)
> Consolidate git repo reset instructions in "Setting Up the Project"

- manuscript/implementing_kanban/02_implementing_store_and_actions.md
- project_source/implementing_kanban/02_implementing_store_and_actions/kanban-app/app/components/App.jsx
- project_source/implementing_kanban/03_implementing_persistency/kanban-app/app/components/App.jsx
In the rest of the chapter this is all done via `this.props.NoteActions....`, had me confused for a bit.
> Call NoteActions consistently via this.props
